import type { Store, Theme, Story, Condition, Provider } from "./types";

export const SEED_CONDITIONS: Condition[] = [
  {
    slug: "addiction",
    label: "Addiction & substance use",
    short: "Addiction",
    description:
      "Loving someone using or in recovery from alcohol, drugs, or other compulsive use.",
    tint: "clay",
  },
  {
    slug: "mental-health",
    label: "Mental health",
    short: "Mental health",
    description:
      "Depression, anxiety, bipolar, schizophrenia, PTSD, OCD — the full spectrum, and the people loving someone through it.",
    tint: "sage",
  },
  {
    slug: "eating-disorders",
    label: "Eating disorders",
    short: "Eating disorders",
    description:
      "Anorexia, bulimia, binge eating, ARFID. The dinner table, the bathroom door, the relapse you can&rsquo;t see.",
    tint: "rose",
  },
  {
    slug: "grief-loss",
    label: "Grief, chronic illness & loss",
    short: "Grief & loss",
    description:
      "Caregiving through chronic illness or dementia, anticipatory grief, and grief after a loss.",
    tint: "amber",
  },
];

export const SEED_THEMES: Theme[] = [
  {
    slug: "parent-of",
    label: "Parent of someone affected",
    short: "Parent of",
    description:
      "For mothers, fathers, and caregivers walking alongside a child living with this.",
    tint: "sage",
  },
  {
    slug: "child-of",
    label: "Child of someone affected",
    short: "Child of",
    description:
      "For people who grew up with this in the home — at any age, still figuring out what it shaped.",
    tint: "clay",
  },
  {
    slug: "partner-of",
    label: "Partner or spouse",
    short: "Partner of",
    description:
      "For people loving someone through this — actively, in recovery, or somewhere in between.",
    tint: "rose",
  },
  {
    slug: "sibling-of",
    label: "Sibling",
    short: "Sibling",
    description:
      "For brothers and sisters carrying the particular weight of watching a sibling struggle.",
    tint: "amber",
  },
  {
    slug: "living-with-it",
    label: "Living with it myself, too",
    short: "Living with it",
    description:
      "For people in their own recovery or treatment who also carry the family side of the story.",
    tint: "sage",
  },
  {
    slug: "grieving",
    label: "Grieving",
    short: "Grieving",
    description:
      "For those carrying loss — recent, distant, or anticipatory.",
    tint: "sand",
  },
  {
    slug: "first-year",
    label: "First year of all this",
    short: "First year",
    description: "Newer to this. Still learning the shape of it.",
    tint: "sage",
  },
  {
    slug: "long-haul",
    label: "Years into it",
    short: "Long haul",
    description: "Years deep. Some days steady, some days not.",
    tint: "clay",
  },
];

export const SEED_STORIES: Story[] = [
  // ── ADDICTION ──────────────────────────────────────────────────────────
  {
    id: "story_001",
    pseudonym: "QuietRiver42",
    conditionSlugs: ["addiction"],
    themeSlugs: ["parent-of", "long-haul"],
    title: "He called from a payphone last Tuesday",
    body: "I hadn't heard his voice in seven months. He didn't ask for money. He just wanted to know if the dog was still alive. I said yes, and we both stayed on the line not saying anything for almost a minute. I don't know what to do with that minute. I keep replaying it.",
    reactions: { me_too: 47, thinking_of_you: 89, thank_you: 23 },
    status: "approved",
    createdAt: "2026-04-28T09:14:00.000Z",
    approvedAt: "2026-04-28T11:02:00.000Z",
  },
  {
    id: "story_002",
    pseudonym: "GentleHarbor18",
    conditionSlugs: ["addiction"],
    themeSlugs: ["child-of"],
    title: "I'm 34 and I still flinch when the front door opens",
    body: "My dad has been sober for nine years. I love him. We have a good relationship now. But my body hasn't caught up. Every time I'm home for the holidays and I hear the front door at night, I am eight years old again. I don't know how to tell him that without hurting him.",
    reactions: { me_too: 134, thinking_of_you: 56, thank_you: 41 },
    status: "approved",
    createdAt: "2026-04-26T17:45:00.000Z",
    approvedAt: "2026-04-26T19:10:00.000Z",
  },
  {
    id: "story_003",
    pseudonym: "SteadyPine07",
    conditionSlugs: ["addiction"],
    themeSlugs: ["partner-of", "first-year"],
    title: "The first time I went to Al-Anon",
    body: "I sat in the parking lot for 22 minutes before I could go in. I was sure everyone would be able to tell I didn't belong. I cried before anyone said hello. A woman next to me handed me a tissue without looking at me, like she'd done it a thousand times. I think she had.",
    reactions: { me_too: 78, thinking_of_you: 31, thank_you: 92 },
    status: "approved",
    createdAt: "2026-04-25T20:33:00.000Z",
    approvedAt: "2026-04-25T22:01:00.000Z",
  },
  {
    id: "story_004",
    pseudonym: "BraveMeadow33",
    conditionSlugs: ["addiction", "grief-loss"],
    themeSlugs: ["sibling-of", "grieving"],
    title: "The anniversary is next week",
    body: "Three years since my brother. People stop bringing him up around year two. They think they're being kind. I want to talk about him so badly. I want someone to say his name without it being a crisis. I'm just going to write it here. Daniel. Daniel. Daniel.",
    reactions: { me_too: 56, thinking_of_you: 218, thank_you: 87 },
    status: "approved",
    createdAt: "2026-04-22T11:08:00.000Z",
    approvedAt: "2026-04-22T12:30:00.000Z",
  },
  {
    id: "story_005",
    pseudonym: "WarmCedar91",
    conditionSlugs: ["addiction"],
    themeSlugs: ["sibling-of"],
    title: "I am tired of being the easy one",
    body: "My sister is the one in recovery and I am the one who is fine. I have been the one who is fine since I was twelve. I am thirty now and last week I cried in a Trader Joe's because they were out of frozen mango and I think it wasn't really about the mango.",
    reactions: { me_too: 201, thinking_of_you: 64, thank_you: 38 },
    status: "approved",
    createdAt: "2026-04-20T08:22:00.000Z",
    approvedAt: "2026-04-20T10:14:00.000Z",
  },
  {
    id: "story_006",
    pseudonym: "TenderShore52",
    conditionSlugs: ["addiction"],
    themeSlugs: ["living-with-it", "parent-of"],
    title: "Both sides of it",
    body: "I have eleven years. My oldest is 16 months into his own thing. The hardest part is knowing exactly what he is feeling and not being able to do it for him. I sat on the porch last night and just let myself say out loud, I cannot want this for him more than he wants it for himself.",
    reactions: { me_too: 89, thinking_of_you: 73, thank_you: 112 },
    status: "approved",
    createdAt: "2026-04-18T22:50:00.000Z",
    approvedAt: "2026-04-19T07:00:00.000Z",
  },
  {
    id: "story_007",
    pseudonym: "RootedTide03",
    conditionSlugs: ["addiction"],
    themeSlugs: ["partner-of"],
    title: "Boundaries are not a punishment",
    body: "It took me three years of therapy to understand that. I kept thinking if I could just love him correctly, I could love him into being okay. The boundary I set last month is not because I love him less. It is because I finally believed that I am a person too.",
    reactions: { me_too: 167, thinking_of_you: 44, thank_you: 102 },
    status: "approved",
    createdAt: "2026-03-30T10:18:00.000Z",
    approvedAt: "2026-03-30T11:50:00.000Z",
  },

  // ── MENTAL HEALTH ──────────────────────────────────────────────────────
  {
    id: "story_101",
    pseudonym: "OpenWillow14",
    conditionSlugs: ["mental-health"],
    themeSlugs: ["partner-of", "long-haul"],
    title: "She hasn't left the apartment in eleven days",
    body: "I am trying to stay cheerful in a way that doesn't feel performative, and I think I am failing at it. I bring her tea. I sit on the floor next to the couch. I told my boss I was sick today because I didn't want to leave her alone. I am also tired. Both things are true.",
    reactions: { me_too: 188, thinking_of_you: 76, thank_you: 41 },
    status: "approved",
    createdAt: "2026-04-30T07:11:00.000Z",
    approvedAt: "2026-04-30T08:45:00.000Z",
  },
  {
    id: "story_102",
    pseudonym: "HopefulBrook22",
    conditionSlugs: ["mental-health"],
    themeSlugs: ["sibling-of", "long-haul"],
    title: "My brother stopped taking the pills again",
    body: "He always tells me first. I don't know why. I am not the oldest, I am not the closest, I am not even in the same state. But I am the one who picks up at 2am. He is brilliant when he is up. He is funny when he is up. The part nobody warns you about is missing the up.",
    reactions: { me_too: 142, thinking_of_you: 58, thank_you: 27 },
    status: "approved",
    createdAt: "2026-04-27T14:38:00.000Z",
    approvedAt: "2026-04-27T16:00:00.000Z",
  },
  {
    id: "story_103",
    pseudonym: "CalmField60",
    conditionSlugs: ["mental-health"],
    themeSlugs: ["child-of", "first-year"],
    title: "Mom's voice on the phone",
    body: "I can tell within four words. I used to think that was a superpower. Now I think it is just the small fact of being the daughter of a woman with bad anxiety. I am 27 and I have been managing my mother's nervous system since I was, what, eight? I am only just learning that this is a thing that happened to me.",
    reactions: { me_too: 224, thinking_of_you: 61, thank_you: 88 },
    status: "approved",
    createdAt: "2026-04-24T19:02:00.000Z",
    approvedAt: "2026-04-24T20:50:00.000Z",
  },
  {
    id: "story_104",
    pseudonym: "MendedStone77",
    conditionSlugs: ["mental-health"],
    themeSlugs: ["partner-of", "first-year"],
    title: "He's home from the hospital",
    body: "Five days. We are walking around each other like the floor is glass. I don't know how to be normal. I don't know if I am allowed to laugh at the show we used to laugh at. I asked him if he wanted soup and he cried and I cried and then we ate soup. That was today. That was something.",
    reactions: { me_too: 67, thinking_of_you: 211, thank_you: 54 },
    status: "approved",
    createdAt: "2026-04-15T16:22:00.000Z",
    approvedAt: "2026-04-15T18:11:00.000Z",
  },

  // ── EATING DISORDERS ───────────────────────────────────────────────────
  {
    id: "story_201",
    pseudonym: "PatientLantern11",
    conditionSlugs: ["eating-disorders"],
    themeSlugs: ["parent-of", "first-year"],
    title: "Dinner is the longest thirty minutes of my day",
    body: "I am supposed to be relaxed. I am supposed to model an easy relationship with food. My daughter is supposed to feel safe. Meanwhile I am cataloging every bite. I am rehearsing what I will say if she asks to be excused. The dietitian said this would get easier. Today is not that day.",
    reactions: { me_too: 119, thinking_of_you: 88, thank_you: 35 },
    status: "approved",
    createdAt: "2026-04-29T18:50:00.000Z",
    approvedAt: "2026-04-29T20:14:00.000Z",
  },
  {
    id: "story_202",
    pseudonym: "EarnestCove45",
    conditionSlugs: ["eating-disorders"],
    themeSlugs: ["sibling-of", "long-haul"],
    title: "I caught my own reflection looking like her",
    body: "I haven't been okay either. I just hide it better. My sister has been the official sick one in our family since she was 14. I am 22 now and I think my body has been quietly copying her for years and nobody noticed because she was the one with the chart. I am writing this from my dorm. I think I need to tell someone.",
    reactions: { me_too: 98, thinking_of_you: 167, thank_you: 73 },
    status: "approved",
    createdAt: "2026-04-23T22:14:00.000Z",
    approvedAt: "2026-04-23T23:55:00.000Z",
  },
  {
    id: "story_203",
    pseudonym: "KindHearth08",
    conditionSlugs: ["eating-disorders"],
    themeSlugs: ["partner-of"],
    title: "She wants to celebrate the gain",
    body: "Her dietitian said it. The number on the scale that, two years ago, would have wrecked her, was the number she was fighting toward. She came home glowing. She wanted to go out for ice cream. I went. I held her hand. I am proud of her in a way I cannot describe. I am also terrified, in a way I am not allowed to be in front of her.",
    reactions: { me_too: 76, thinking_of_you: 132, thank_you: 154 },
    status: "approved",
    createdAt: "2026-04-21T13:37:00.000Z",
    approvedAt: "2026-04-21T15:10:00.000Z",
  },
  {
    id: "story_204",
    pseudonym: "SoftBeacon29",
    conditionSlugs: ["eating-disorders"],
    themeSlugs: ["child-of", "long-haul"],
    title: "The scale was the only god in our house",
    body: "My mother wasn't diagnosed with anything. She just lived inside a calorie count for forty years. I learned to be small in a way that wasn't about my body. I am 38 and I am only just learning that meals can be neutral. That hunger is not a moral test. That a sandwich is just a sandwich.",
    reactions: { me_too: 145, thinking_of_you: 49, thank_you: 81 },
    status: "approved",
    createdAt: "2026-04-17T09:55:00.000Z",
    approvedAt: "2026-04-17T11:42:00.000Z",
  },

  // ── GRIEF, CHRONIC ILLNESS & LOSS ──────────────────────────────────────
  {
    id: "story_301",
    pseudonym: "GroundedDawn08",
    conditionSlugs: ["grief-loss"],
    themeSlugs: ["child-of", "long-haul"],
    title: "Mom called the dog by my name today",
    body: "Six years into the dementia. The doctor warned me there would come a stretch where her face would be the same and her voice would be the same and the things she said would belong to a different woman. I think we are in that stretch. I miss her while she is still here. I have been told this is called anticipatory grief. The word does not help.",
    reactions: { me_too: 87, thinking_of_you: 256, thank_you: 132 },
    status: "approved",
    createdAt: "2026-05-02T08:40:00.000Z",
    approvedAt: "2026-05-02T10:11:00.000Z",
  },
  {
    id: "story_302",
    pseudonym: "TenderWillow16",
    conditionSlugs: ["grief-loss"],
    themeSlugs: ["partner-of", "grieving", "long-haul"],
    title: "Three years and I still set the second mug",
    body: "I am almost done with the years where people ask. I have stopped explaining. I will set the second mug until I stop, and there is no one I owe an explanation to. Sometimes I drink from it. Sometimes I just leave it there. It is the smallest gesture of yes you were real and yes you are missed.",
    reactions: { me_too: 94, thinking_of_you: 312, thank_you: 197 },
    status: "approved",
    createdAt: "2026-04-19T07:25:00.000Z",
    approvedAt: "2026-04-19T09:00:00.000Z",
  },
  {
    id: "story_303",
    pseudonym: "BraveCove74",
    conditionSlugs: ["grief-loss"],
    themeSlugs: ["partner-of"],
    title: "He's stable but tired",
    body: "Five years out from the cancer. We are not supposed to call this grief because he is here. But I am quietly grieving the marriage we were going to have. The hikes. The plans. The big easy second half. He is here, and we are figuring out what here looks like, and that is not nothing. It is also not the thing we were promised.",
    reactions: { me_too: 132, thinking_of_you: 148, thank_you: 71 },
    status: "approved",
    createdAt: "2026-04-14T15:48:00.000Z",
    approvedAt: "2026-04-14T17:20:00.000Z",
  },
  {
    id: "story_304",
    pseudonym: "RootedShore55",
    conditionSlugs: ["grief-loss"],
    themeSlugs: ["child-of", "first-year"],
    title: "She wants to die at home",
    body: "I said yes before I had thought about what yes meant. Yes meant the hospital bed in the dining room. Yes meant the chart on the fridge. Yes meant being the one who measures the morphine. I am terrified and I am also somehow grateful, in a quiet way that I would not have predicted, to be the one she trusted to do this.",
    reactions: { me_too: 41, thinking_of_you: 287, thank_you: 124 },
    status: "approved",
    createdAt: "2026-04-08T20:30:00.000Z",
    approvedAt: "2026-04-08T22:14:00.000Z",
  },
];

export const SEED_PROVIDERS: Provider[] = [
  {
    id: "prov_001",
    name: "Dr. Maya Tanaka",
    credentials: "PhD, LMFT",
    title: "Family therapist · Addiction & substance use",
    blurb:
      "Twenty years of work with families navigating active use, recovery, and relapse. CRAFT-trained.",
    conditionSlugs: ["addiction"],
    modalities: ["family", "couples", "individual"],
    format: "both",
    city: "Oakland",
    state: "CA",
    secondPatientTrained: true,
    vettedBy: "Stanford Medicine",
    takingClients: true,
  },
  {
    id: "prov_002",
    name: "Renee Carter",
    credentials: "LCSW",
    title: "Caregiver coach · Adult children of",
    blurb:
      "For people in their 20s–40s still figuring out what growing up around addiction or untreated mental illness shaped. ACA-informed.",
    conditionSlugs: ["addiction", "mental-health"],
    modalities: ["individual", "group"],
    format: "telehealth",
    secondPatientTrained: true,
    vettedBy: "Hazelden Betty Ford",
    takingClients: true,
  },
  {
    id: "prov_003",
    name: "Dr. Aisha Bello",
    credentials: "PsyD",
    title: "Family therapist · Eating disorders",
    blurb:
      "FBT-certified. Works with parents of teens in recovery from anorexia and bulimia. Sliding scale available.",
    conditionSlugs: ["eating-disorders"],
    modalities: ["family", "individual"],
    format: "both",
    city: "Denver",
    state: "CO",
    secondPatientTrained: true,
    vettedBy: "Eating Recovery Center",
    takingClients: true,
  },
  {
    id: "prov_004",
    name: "Sam Levenson",
    credentials: "LMFT",
    title: "Couples therapist · Mental illness in the marriage",
    blurb:
      "For partners of someone living with depression, bipolar, or PTSD. Gottman + ACT trained.",
    conditionSlugs: ["mental-health"],
    modalities: ["couples", "individual"],
    format: "telehealth",
    secondPatientTrained: true,
    vettedBy: "UCSF Family Resource",
    takingClients: true,
  },
  {
    id: "prov_005",
    name: "Dr. Ines Romero",
    credentials: "MD, psychiatrist",
    title: "Family psychiatrist · Severe & persistent mental illness",
    blurb:
      "Family-centered care for households navigating schizophrenia, schizoaffective disorder, and severe bipolar.",
    conditionSlugs: ["mental-health"],
    modalities: ["family", "individual"],
    format: "in_person",
    city: "Boston",
    state: "MA",
    secondPatientTrained: true,
    vettedBy: "McLean Hospital",
    takingClients: false,
  },
  {
    id: "prov_006",
    name: "Theo Park",
    credentials: "LCSW",
    title: "Grief therapist · Anticipatory and post-loss",
    blurb:
      "For caregivers of someone with terminal illness, dementia, or in late-stage recovery. Slow, patient work.",
    conditionSlugs: ["grief-loss"],
    modalities: ["individual", "group"],
    format: "both",
    city: "Seattle",
    state: "WA",
    secondPatientTrained: true,
    vettedBy: "Hospice Foundation of America",
    takingClients: true,
  },
  {
    id: "prov_007",
    name: "Dr. Priya Nair",
    credentials: "PhD",
    title: "Caregiver wellness · Dementia & chronic illness",
    blurb:
      "Specializes in burnout, anticipatory grief, and identity recovery for full-time family caregivers.",
    conditionSlugs: ["grief-loss"],
    modalities: ["individual", "coaching", "group"],
    format: "telehealth",
    secondPatientTrained: true,
    vettedBy: "Alzheimer's Association",
    takingClients: true,
  },
  {
    id: "prov_008",
    name: "Lena Okafor",
    credentials: "LMFT",
    title: "Sibling specialist",
    blurb:
      "Works specifically with adult siblings of someone with addiction, severe mental illness, or an eating disorder. The sibling experience is its own thing.",
    conditionSlugs: ["addiction", "mental-health", "eating-disorders"],
    modalities: ["individual", "group"],
    format: "telehealth",
    secondPatientTrained: true,
    vettedBy: "Beside clinical board",
    takingClients: true,
  },
  {
    id: "prov_009",
    name: "Dr. Marcus Hale",
    credentials: "PsyD",
    title: "Parent coach · Eating disorder recovery at home",
    blurb:
      "FBT-certified parent coaching between weekly sessions with the family team. For the in-between hours that are the hardest.",
    conditionSlugs: ["eating-disorders"],
    modalities: ["coaching", "family"],
    format: "telehealth",
    secondPatientTrained: true,
    vettedBy: "Eating Recovery Center",
    takingClients: true,
  },
  {
    id: "prov_010",
    name: "Sofia Gutierrez",
    credentials: "LCSW, CADC-II",
    title: "Family addiction counselor",
    blurb:
      "Bilingual (English/Spanish). Specializes in immigrant and first-generation families navigating addiction with cultural shame.",
    conditionSlugs: ["addiction"],
    modalities: ["family", "individual", "group"],
    format: "both",
    city: "Los Angeles",
    state: "CA",
    secondPatientTrained: true,
    vettedBy: "Hazelden Betty Ford",
    takingClients: true,
  },
];

export function freshStore(): Store {
  return {
    conditions: SEED_CONDITIONS,
    themes: SEED_THEMES,
    stories: SEED_STORIES,
    users: [],
    providers: SEED_PROVIDERS,
  };
}
